In [ ]:
import numpy as np

# Task 1

arr1_1 = np.arange(0, 100)

arr1_2 = np.ones((3, 3))

arr1_3 = np.full((2, 4), 7)

arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[38 19 24 24 19]
 [12 43 32 31 42]]


In [ ]:
# Task 2

import numpy as np

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1 = data[2, 3]
row2_2 = data[0]
col2_3 = data[:, -1]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [ ]:
# Task 3

arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("\narr3_2:\n", arr3_2)
print("\nNumber of even elements:", even_count3_3)

arr3_1:
 [[ 2  8  1  5 12]
 [ 8 17  5  9  2]
 [ 8  7  5  4 11]
 [ 1 18 18  5 10]]

arr3_2:
 [[ 0  0  0  0 12]
 [ 0 17  0  0  0]
 [ 0  0  0  0 11]
 [ 0 18 18  0 10]]

Number of even elements: 10


In [ ]:
# Task 4

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)

mean_cols4_2 = np.mean(arr4_1, axis=0)

max_rows4_3 = np.max(arr4_1, axis=1)

std4_4 = np.std(arr4_1)

print("Sum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation:", std4_4)

Sum of all elements: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum value in each row: [12 15 20]
Standard deviation: 5.2493385826745405


In [ ]:
# Task 5

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)

reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_arr5_4_copy = reshaped_arr5_2.flatten()

print("Original array:\n", arr5_1)

print("\n4x6 reshaped array:\n", reshaped_arr5_2)

print("\n2x3x4 reshaped array:\n", reshaped_arr5_3)

print("\nFlattened using ravel():\n", flattened_arr5_4)

print("\nFlattened using flatten():\n", flattened_arr5_4_copy)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4x6 reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

2x3x4 reshaped array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
# Task 6

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar

result6_2 = arr6_1 + vector

print("Original array:\n", arr6_1)

print("\nAfter adding scalar (10):\n", result6_1)

print("\nAfter adding vector [100, 200, 300]:\n", result6_2)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding scalar (10):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

After adding vector [100, 200, 300]:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [ ]:
# Task 7

original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]

view_arr7[0] = 99

print("After modifying view_arr7:")
print("original_arr7:", original_arr7)
print("view_arr7:", view_arr7)

copy_arr7 = original_arr7.copy()

copy_arr7[-1] = 0

print("\nAfter modifying copy_arr7:")
print("original_arr7:", original_arr7)
print("copy_arr7:", copy_arr7)

After modifying view_arr7:
original_arr7: [99  2  3  4  5]
view_arr7: [99  2  3  4  5]

After modifying copy_arr7:
original_arr7: [99  2  3  4  5]
copy_arr7: [99  2  3  4  0]


In [ ]:
# Task 8

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print("Vertical Stack:\n", vstack_arr8_1)

print("\nHorizontal Stack:\n", hstack_arr8_2)

print("\nCombined Array:\n", combined_arr8_3)

print("\nPart 1:\n", part1)
print("\nPart 2:\n", part2)
print("\nPart 3:\n", part3)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Combined Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Part 1:
 [[1 2]
 [3 4]]

Part 2:
 [[5 6]
 [7 8]]

Part 3:
 [[ 9 10]]


In [ ]:
# Task 9

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)
print("Sorted 1D array:", sorted_arr9_1)
print("\nColumn-wise sorted 2D array:\n", sorted_cols9_2)
print("\nIndex of value 9:", idx9_3)
print("\nIndex of maximum value:", max_idx9_4)

Sorted 1D array: [1 2 3 4 5 6 7 8 9]

Column-wise sorted 2D array:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

Index of value 9: (array([4]),)

Index of maximum value: 4
