In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# Task 1

s1_1 = pd.Series([10, 20, 30, 40, 50])

np_array1_2 = np.random.randint(1, 101, size=(3, 4))

df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)
print("Series:")
print(s1_1)
print("\nNumPy Array:")
print(np_array1_2)
print("\nDataFrame:")
print(df1_3)

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[15 52 37 38]
 [51 45 18 79]
 [83 34 65 17]]

DataFrame:
    A   B   C   D
0  15  52  37  38
1  51  45  18  79
2  83  34  65  17


In [ ]:
# Task 2: Synthetic Data Generation

df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01',
                          end='2023-04-10',
                          periods=100),
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=100
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=100
    ),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

sales_nan_idx = np.random.choice(df_sales.index,
                                 size=5,
                                 replace=False)

df_sales.loc[sales_nan_idx, 'Sales'] = np.nan

qty_nan_idx = np.random.choice(df_sales.index,
                               size=3,
                               replace=False)

df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

print(df_sales.head())

        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  617.0       7.0
1 2023-01-02  North     Mouse  570.0       3.0
2 2023-01-03  North  Keyboard  277.0       4.0
3 2023-01-04   West   Monitor  373.0       7.0
4 2023-01-05   West   Monitor  639.0       4.0


In [ ]:
# Task 3

df3_1 = df_sales[['Region', 'Sales']]

df3_2 = df_sales[df_sales['Product'] == 'Laptop']

df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

monitor_rows = df_sales[df_sales['Product'] == 'Monitor']

first_monitor_index = monitor_rows.index[0]

val3_4 = df_sales.loc[first_monitor_index, 'Sales']

print("\ndf3_1:")
print(df3_1.head())
print("\ndf3_2:")
print(df3_2.head())
print("\ndf3_3:")
print(df3_3.head())
print("\nFirst Monitor Sales value:", val3_4)


df3_1:
  Region  Sales
0   West  617.0
1  North  570.0
2  North  277.0
3   West  373.0
4   West  639.0

df3_2:
         Date Region Product  Sales  Quantity
18 2023-01-19   West  Laptop  568.0       9.0
21 2023-01-22   West  Laptop  616.0       3.0
26 2023-01-27   West  Laptop  739.0       6.0
27 2023-01-28   East  Laptop  826.0       3.0
28 2023-01-29  South  Laptop  735.0       9.0

df3_3:
         Date Region Product  Sales  Quantity
9  2023-01-10   East   Mouse  702.0       6.0
14 2023-01-15   East   Mouse  541.0       2.0
27 2023-01-28   East  Laptop  826.0       3.0
38 2023-02-08   East  Laptop  857.0       7.0
43 2023-02-13   East  Laptop  954.0      10.0

First Monitor Sales value: 373.0


In [ ]:
# Task 4: Data Cleaning

missing_counts4_1 = df_sales.isnull().sum()

df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = (
    df4_2_filled['Sales']
    .fillna(sales_mean)
)
df4_3_dropped = df_sales.dropna()
print("Missing values in each column:")
print(missing_counts4_1)
print("\nDataFrame with Sales NaNs filled:")
print(df4_2_filled.head())
print("\nDataFrame after dropping NaNs:")
print(df4_3_dropped.head())

Missing values in each column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

DataFrame with Sales NaNs filled:
        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  617.0       7.0
1 2023-01-02  North     Mouse  570.0       3.0
2 2023-01-03  North  Keyboard  277.0       4.0
3 2023-01-04   West   Monitor  373.0       7.0
4 2023-01-05   West   Monitor  639.0       4.0

DataFrame after dropping NaNs:
        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  617.0       7.0
1 2023-01-02  North     Mouse  570.0       3.0
2 2023-01-03  North  Keyboard  277.0       4.0
3 2023-01-04   West   Monitor  373.0       7.0
4 2023-01-05   West   Monitor  639.0       4.0


In [ ]:
# Task 5: Data Manipulation
df_sales['Total_Revenue'] = (
    df_sales['Sales'] * df_sales['Quantity']
)
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)
df5_3_grouped_region = (
    df_sales
    .groupby('Region')[['Sales', 'Quantity']]
    .sum()
)
df5_4_grouped_product = (
    df_sales
    .groupby('Product')['Sales']
    .mean()
)
print("\nData with Total_Revenue:")
print(df_sales.head())
print("\nSorted DataFrame:")
print(df5_2_sorted.head())
print("\nGrouped by Region:")
print(df5_3_grouped_region)
print("\nAverage Sales by Product:")
print(df5_4_grouped_product)


Data with Total_Revenue:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   West  Keyboard  617.0       7.0         4319.0
1 2023-01-02  North     Mouse  570.0       3.0         1710.0
2 2023-01-03  North  Keyboard  277.0       4.0         1108.0
3 2023-01-04   West   Monitor  373.0       7.0         2611.0
4 2023-01-05   West   Monitor  639.0       4.0         2556.0

Sorted DataFrame:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   West  Keyboard  617.0       7.0         4319.0
1 2023-01-02  North     Mouse  570.0       3.0         1710.0
2 2023-01-03  North  Keyboard  277.0       4.0         1108.0
3 2023-01-04   West   Monitor  373.0       7.0         2611.0
4 2023-01-05   West   Monitor  639.0       4.0         2556.0

Grouped by Region:
          Sales  Quantity
Region                   
East    10500.0     103.0
North   10492.0      96.0
South   14111.0     109.0
West    19688.0     194.0

Average Sales by Product:
Product
